[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ty.rules]
unresolved-import = "ignore"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
